[package]
name = "refund-vault"
version = "0.2.0"
edition = "2021"
rust-version.workspace = true

[dependencies]
soroban-sdk.workspace = true

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
proptest.workspace = true
receipt-anchor = { path = "../receipt-anchor" }

[lints]
workspace = true

[lib]
crate-type = ["lib"
             ,
             "cdylib"
]
